#pragma once
#include <minwindef.h>

typedef BOOL(_stdcall *pInitHardWare)();
typedef BOOL (_stdcall *pUnintHWare)();
typedef BOOL (_stdcall *pVTIsSDKCorrect)();
typedef BOOL (_stdcall *pKZGetVideoSize)(USHORT *w,USHORT *h);
typedef BOOL (_stdcall *pKZPreviewStartVideo)();
typedef BOOL (_stdcall *pKZPreviewOneVideoFrameRGB)(LPVOID rgbbuf);
typedef BOOL (_stdcall *pKZPreviewStopVideo)();
typedef BOOL (_stdcall *pKZSetUploadMode)();
typedef BOOL (_stdcall *pKZSetNormalStoreMode)();
typedef DWORD (_stdcall *pKZUpload)(LPVOID	lpBuffer);
typedef BOOL (_stdcall *pKZCapture)();
typedef BOOL (_stdcall *pKZFlashModeSet)(USHORT	flashmode);
typedef BOOL (_stdcall *pKZFireOutsideFlash)();
typedef BOOL (_stdcall *pKZFirePower_OutsideFlash)(USHORT	Duration);
typedef BOOL (_stdcall *pKZIsUseCaptureAF)(USHORT IsUse);
typedef BOOL (_stdcall *pKZAFMode)(USHORT afmode);
typedef BOOL (_stdcall *pKZFlashCharge)(USHORT bcharge);
typedef BOOL (_stdcall *pKZEnterPMode)();
typedef BOOL (_stdcall *pKZEnterAMode)();
typedef BOOL (_stdcall *pKZEnterSMode)();
typedef BOOL (_stdcall *pKZEnterMMode)();
typedef BOOL (_stdcall *pKZASM_AVSET)(USHORT bAV);
typedef BOOL (_stdcall *pKZASM_TVSET)(USHORT tvsetvalue);
typedef BOOL (_stdcall *pKZDisablePowerSave)();
typedef BOOL (_stdcall *pKZEnablePowerSave)();
typedef BOOL (_stdcall *pKZLcdOn)();
typedef BOOL (_stdcall *pKZLcdOff)();
typedef BOOL (_stdcall *pKZKEYOn)();
typedef BOOL (_stdcall *pKZKEYOff)();
typedef BOOL (_stdcall *pKZLensClose)();
typedef BOOL (_stdcall *pKZLensOut)();
typedef BOOL (_stdcall *pKZPowerOff)();
typedef DWORD (_stdcall *pKZGetZoomPos)();
typedef BOOL (_stdcall *pKZZoom)(USHORT zoomnumber);
typedef DWORD (_stdcall *pKZGetFocusPos)();
typedef BOOL (_stdcall *pKZFocusPos)(USHORT focuspos);
typedef DWORD (_stdcall *pKZIsLensMoving)();
typedef DWORD (_stdcall *pKZIsFlashCharging)();
typedef BOOL (_stdcall *pKZImageSizeSet)(USHORT imagesize);
typedef BOOL (_stdcall *pKZSetQuality)(USHORT quality);
typedef BOOL (_stdcall *pKZBiasSet)(USHORT bias);
typedef BOOL (_stdcall *pKZAWBMode)(USHORT awbmode,USHORT effect);
typedef BOOL (_stdcall *pKZISOSet)(USHORT iso);
typedef BOOL (_stdcall *pKZMeterMode)(USHORT meter);
typedef BOOL (_stdcall *pKZSharpMode)(USHORT sharp);
typedef BOOL (_stdcall *pKZModify_para)(USHORT item,USHORT data);
typedef BOOL (_stdcall *pKZIdle)();
typedef BOOL (_stdcall *pKZPreview)();
typedef BOOL (_stdcall *pKZInitDSCParam)();
typedef BOOL (_stdcall *pKZAFAreaSet)(USHORT afarea);
typedef BOOL (_stdcall *pKZAF)();
typedef BOOL (_stdcall *pKZIsDoingAF)();
typedef BOOL (_stdcall *pKZSwitchOSDOnOff)(USHORT osdon);
typedef BOOL (_stdcall *pKZAWBCustomRGB)(USHORT r,USHORT g,USHORT b);
typedef BOOL (_stdcall *pKZGetWBCustomRGB)(USHORT *r,USHORT *g,USHORT *b);
typedef DWORD (_stdcall *pKZVersion)();

static pInitHardWare	InitHardWare = NULL;
static pUnintHWare	UnintHWare = NULL;
static pVTIsSDKCorrect	VTIsSDKCorrect = NULL;
static pKZGetVideoSize	KZGetVideoSize = NULL;
static pKZPreviewStartVideo	KZPreviewStartVideo = NULL;
static pKZPreviewOneVideoFrameRGB	KZPreviewOneVideoFrameRGB = NULL;
static pKZPreviewStopVideo	KZPreviewStopVideo = NULL;
static pKZSetUploadMode	KZSetUploadMode = NULL;
static pKZSetNormalStoreMode	KZSetNormalStoreMode = NULL;
static pKZUpload	KZUpload = NULL;
static pKZCapture	KZCapture = NULL;
static pKZFlashModeSet	KZFlashModeSet = NULL;
static pKZFireOutsideFlash	KZFireOutsideFlash = NULL;
static pKZFirePower_OutsideFlash	KZFirePower_OutsideFlash = NULL;
static pKZIsUseCaptureAF	KZIsUseCaptureAF = NULL;
static pKZAFMode	KZAFMode = NULL;
static pKZFlashCharge	KZFlashCharge = NULL;
static pKZEnterPMode	KZEnterPMode = NULL;
static pKZEnterAMode	KZEnterAMode = NULL;
static pKZEnterSMode	KZEnterSMode = NULL;
static pKZEnterMMode	KZEnterMMode = NULL;
static pKZASM_AVSET	KZASM_AVSET = NULL;
static pKZASM_TVSET	KZASM_TVSET = NULL;
static pKZDisablePowerSave	KZDisablePowerSave = NULL;
static pKZEnablePowerSave	KZEnablePowerSave = NULL;
static pKZLcdOn	KZLcdOn = NULL;
static pKZLcdOff	KZLcdOff = NULL;
static pKZKEYOn	KZKEYOn = NULL;
static pKZKEYOff	KZKEYOff = NULL;
static pKZLensClose	KZLensClose = NULL;
static pKZLensOut	KZLensOut = NULL;
static pKZPowerOff	KZPowerOff = NULL;
static pKZGetZoomPos	KZGetZoomPos = NULL;
static pKZZoom	KZZoom = NULL;
static pKZGetFocusPos	KZGetFocusPos = NULL;
static pKZFocusPos	KZFocusPos = NULL;
static pKZIsLensMoving	KZIsLensMoving = NULL;
static pKZIsFlashCharging	KZIsFlashCharging = NULL;
static pKZImageSizeSet	KZImageSizeSet = NULL;
static pKZSetQuality	KZSetQuality = NULL;
static pKZBiasSet	KZBiasSet = NULL;
static pKZAWBMode	KZAWBMode = NULL;
static pKZISOSet	KZISOSet = NULL;
static pKZMeterMode	KZMeterMode = NULL;
static pKZSharpMode	KZSharpMode = NULL;
static pKZModify_para	KZModify_para = NULL;
static pKZIdle	KZIdle = NULL;
static pKZPreview	KZPreview = NULL;
static pKZInitDSCParam	KZInitDSCParam = NULL;
static pKZAFAreaSet	KZAFAreaSet = NULL;
static pKZAF	KZAF = NULL;
static pKZIsDoingAF	KZIsDoingAF = NULL;
static pKZSwitchOSDOnOff	KZSwitchOSDOnOff = NULL;
static pKZAWBCustomRGB	KZAWBCustomRGB = NULL;
static pKZGetWBCustomRGB	KZGetWBCustomRGB = NULL;
static pKZVersion	KZVersion = NULL;
 